<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Settings</name>
   <tag></tag>
   <elementGuidId>d6e30804-0e41-4ed0-87a5-c99a73fae336</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.nav.navbar-nav > li.ng-scope > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/section/div[2]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Settings&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>73e7fbdb-f63b-4399-b9f3-da1b33b4069c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/local-sandbox/admin/settings</value>
      <webElementGuid>5f5b5730-56ba-4f7f-a641-00cae34c7177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Settings </value>
      <webElementGuid>e22fd7a2-84ad-4a7d-a753-d61e8c29b44a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/section[@class=&quot;app-header navbar ng-scope&quot;]/div[@class=&quot;collapse pos-rlt navbar-collapse box-shadow bg-success ng-scope&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;ng-scope&quot;]/a[1]</value>
      <webElementGuid>f20c2da8-27d0-4551-b0fd-de987de8e838</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/section/div[2]/ul/li[2]/a</value>
      <webElementGuid>db5ff4ea-1368-476e-8897-3949e83d6a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Settings')]</value>
      <webElementGuid>51153a48-10a4-4eef-bf6d-66d4970f5a29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ReachFive'])[1]/following::a[1]</value>
      <webElementGuid>b21ff2a0-b9d7-4ef2-ba00-c94a02ed12f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sandbox'])[1]/following::a[2]</value>
      <webElementGuid>c391f8ff-75f4-4346-a3ac-263d5d48deb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Root'])[1]/preceding::a[1]</value>
      <webElementGuid>0948c8b5-7462-4135-9a17-fab6f468f412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Account'])[1]/preceding::a[3]</value>
      <webElementGuid>bba1fd9f-1c79-4676-ad6c-d533dc6639c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Settings']/parent::*</value>
      <webElementGuid>e8b667ea-a805-484c-a7bf-309dc7d29bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/local-sandbox/admin/settings')]</value>
      <webElementGuid>ecf6d667-abbd-43f5-9369-7da718e3c420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>57c36f50-da3a-406c-b377-bb1f22a58689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/local-sandbox/admin/settings' and (text() = ' Settings ' or . = ' Settings ')]</value>
      <webElementGuid>940d721c-d717-4bf9-b361-d67031df8a2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
