<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>login_email</name>
   <tag></tag>
   <elementGuidId>797b48ad-5075-4b01-af34-6880e464481e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vBropV</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@name = 'identifier']//input[@placeholder=‘Email address or phone number’]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'identifier' and @placeholder = 'Email address or phone number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;identifier&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>240e4731-8013-4039-a654-6483e2184403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vBropV</value>
      <webElementGuid>8488be5b-3f52-43bf-8cc9-5f8e4338fd18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>identifier</value>
      <webElementGuid>46a51137-ff2b-488a-9dda-8d3747860f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a30a437d-38fe-4cde-bbb2-f70a000f10c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email address or phone number</value>
      <webElementGuid>9d6e07c6-1db7-4181-89ff-090ebbadc257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Email address or phone number</value>
      <webElementGuid>11de39c2-e291-4906-9528-4c9365e2b92b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>identifier</value>
      <webElementGuid>84fde913-2d48-40aa-b97c-ea433d6c5136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fzqBZW jQwMMR</value>
      <webElementGuid>6138054d-bd0d-4148-b07f-800c664fe43c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vBropV&quot;)</value>
      <webElementGuid>484e3b6b-d619-4347-9746-ac6126ae932b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vBropV']</value>
      <webElementGuid>185bbc08-90dc-4e0e-b3ed-9c1640821e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-container']/div/div/form/div/input</value>
      <webElementGuid>445ec53f-1e85-455d-b4db-9b06f3aac04a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>bf62f14a-2d78-4f5a-9ac5-b84598319038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'vBropV' and @name = 'identifier' and @type = 'text' and @placeholder = 'Email address or phone number' and @title = 'Email address or phone number']</value>
      <webElementGuid>2e4f513e-8039-49b9-900f-dd9297167f9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
