<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Title_Accounts_RootPage</name>
   <tag></tag>
   <elementGuidId>354e29c0-5d94-46d3-bfe1-cde6b0389fe7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.aVOuy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='base-layer']/main/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Accounts (31)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>378398c2-e54d-41d0-99bf-4fe927e52f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aVOuy</value>
      <webElementGuid>4690f7ac-70db-43b0-9094-61ae7afc60b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accounts (31)</value>
      <webElementGuid>b7ce7459-fb93-49c8-8c44-9ca7ad3193bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;base-layer&quot;)/main[@class=&quot;d3KUA&quot;]/div[@class=&quot;W9Owb&quot;]/h1[@class=&quot;aVOuy&quot;]</value>
      <webElementGuid>183b1cd0-641a-42c2-ad52-c3615d1b0739</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='base-layer']/main/div/h1</value>
      <webElementGuid>bb408403-9429-4ead-9ca7-fd37afd74087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nawel Mele'])[1]/following::h1[1]</value>
      <webElementGuid>b7ff2d08-579c-40f6-95d7-1cab3ea4be4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go to account'])[1]/following::h1[1]</value>
      <webElementGuid>8f608329-0741-4338-a105-19f23821b316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New account'])[1]/preceding::h1[1]</value>
      <webElementGuid>dd4820c3-fac4-4e96-a6ab-6fedc8f811fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Only show accounts on the cluster'])[1]/preceding::h1[1]</value>
      <webElementGuid>492da6cd-b20a-465e-9cca-2cd5b46e97e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accounts (31)']/parent::*</value>
      <webElementGuid>058a4da1-bbcd-43ab-baca-3bb6adee810f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>aab108f4-7b7f-4d91-9cc9-03d7b3f9aa22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Accounts (31)' or . = 'Accounts (31)')]</value>
      <webElementGuid>4d87c765-2907-4afd-9ad5-0208db15c9a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
