<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Google</name>
   <tag></tag>
   <elementGuidId>0c32eb92-415a-46f7-80d5-c5efe9e902ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.r5-btn-social.r5-btn-social-google.sc-fzozJi.sc-fzpans.gFDzmB</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-container']/div/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Google&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3c9e87b0-c31e-4991-829d-a1d34a42c893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>r5-btn-social r5-btn-social-google sc-fzozJi sc-fzpans gFDzmB</value>
      <webElementGuid>4b44a4d5-fb0e-43f7-a0e0-cbb931fc03f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Google</value>
      <webElementGuid>b38366f1-d95a-4da3-a24c-67743e0c7e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Google</value>
      <webElementGuid>8b239c70-5450-427e-8a8f-a1d68ae9ce36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-container&quot;)/div[@class=&quot;sc-AxmLO bRvQpG&quot;]/div[1]/div[@class=&quot;r5-social-buttons sc-fzplWN kfkaqq&quot;]/button[@class=&quot;r5-btn-social r5-btn-social-google sc-fzozJi sc-fzpans gFDzmB&quot;]</value>
      <webElementGuid>faf7671a-ed9f-4bb9-94f6-f6f3a1403dc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-container']/div/div/div[2]/button</value>
      <webElementGuid>36a1b590-08f5-49d0-9421-ce8948fd25c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::button[1]</value>
      <webElementGuid>c3d143b2-936a-47aa-99bd-b5cf738bc60d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::button[1]</value>
      <webElementGuid>0b2b3fec-a341-4fa6-bbac-7f0af2bdd12e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Microsoft'])[1]/preceding::button[1]</value>
      <webElementGuid>d474a908-1a2a-4f07-9072-42e9e23774fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>4109d200-b2dd-4f6d-b23c-9e3ecab63f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Google' and (text() = 'Google' or . = 'Google')]</value>
      <webElementGuid>218fdf99-a942-490f-8e88-6a70afcd75dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
