<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email address or phone number_identifier</name>
   <tag></tag>
   <elementGuidId>13c4e9a1-79b3-4aba-814a-ab5ea0e907ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#xVVmff</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='xVVmff']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;identifier&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>482021d2-5a9f-4e01-9cfd-17a271311b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xVVmff</value>
      <webElementGuid>e7415501-8253-4e88-9ffc-d8f184ab5839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>identifier</value>
      <webElementGuid>8bba3f1b-7590-4d5e-a47c-05f4bb6aafc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9edec2f6-27f6-454d-b581-4f9fcac19ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email address or phone number</value>
      <webElementGuid>f84193b9-cb7c-47e0-bd47-a94e8b252256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Email address or phone number</value>
      <webElementGuid>22c7088f-1505-4b71-bd2f-01b59ff7326e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>username webauthn</value>
      <webElementGuid>7a626378-dff2-447a-963b-45f629f91caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>identifier</value>
      <webElementGuid>4e52c2f1-10a8-4ba9-9651-06c6464d053a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fzqBZW jQwMMR</value>
      <webElementGuid>95aa0ea4-4cb5-4439-a94a-495ed99375d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xVVmff&quot;)</value>
      <webElementGuid>eded8b9e-b32b-4793-9156-ab89a213b419</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='xVVmff']</value>
      <webElementGuid>f88d6b83-e330-45f4-a67a-7b4bdfd2036a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-container']/div/div/form/div/input</value>
      <webElementGuid>b5270a5a-4ba7-4a28-8885-579c912d2c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3c337274-7ce7-46cf-b278-ace3b1c145c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'xVVmff' and @name = 'identifier' and @type = 'text' and @placeholder = 'Email address or phone number' and @title = 'Email address or phone number']</value>
      <webElementGuid>65feb834-2ffa-4c92-846a-44f5d03c6ada</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
