<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Filters</name>
   <tag></tag>
   <elementGuidId>a559eb14-4d44-43af-997b-2ba4cde412d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.z3Q7p.gkNlq.Me0lj > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='base-layer']/main/div[2]/div/div[2]/div/div[2]/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Filters&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9d27d13f-7a57-448c-8897-49e28259046a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filters</value>
      <webElementGuid>899c942b-043b-4e09-b72f-045d7d42fee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;base-layer&quot;)/main[@class=&quot;d3KUA&quot;]/div[@class=&quot;cHndV&quot;]/div[1]/div[2]/div[@class=&quot;wiDxe&quot;]/div[@class=&quot;PYQoT&quot;]/div[1]/button[@class=&quot;z3Q7p gkNlq Me0lj&quot;]/span[1]</value>
      <webElementGuid>a13034ea-c2f9-43c0-8b3e-f4b69922557a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='base-layer']/main/div[2]/div/div[2]/div/div[2]/div/button/span</value>
      <webElementGuid>5a7064aa-1bbe-44ae-a284-f20701daf6ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No activity exists for this user.'])[1]/following::span[1]</value>
      <webElementGuid>d4e2dced-c555-41d0-ac44-e26a11da1968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consents'])[1]/following::span[2]</value>
      <webElementGuid>0f3f1a9d-8bc4-4da2-aba0-f06b92eb05d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Filters']/parent::*</value>
      <webElementGuid>02e2add0-2c8d-435c-bfb9-55f072be56e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button/span</value>
      <webElementGuid>04a2fd05-1f8a-4346-9ae2-bd085175d6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Filters' or . = 'Filters')]</value>
      <webElementGuid>1e9e00c3-82e0-4cb3-9daa-5f070de74ecc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
