<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_nawel.melereach5.co</name>
   <tag></tag>
   <elementGuidId>af4ef1fc-2fb9-4f92-86ca-e61b909e6c71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='base-layer']/main/div[2]/div[2]/table/tbody/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;nawel.mele@reach5.co&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>53da8e63-bc2f-4552-b4df-e29134d796de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qIBX3 vpuDG</value>
      <webElementGuid>54e49dc4-a727-419d-8b87-15f093b5ad84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>nawel.mele@reach5.co</value>
      <webElementGuid>12b3d6ee-330c-40be-adf6-2f48baab4872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;base-layer&quot;)/main[@class=&quot;d3KUA&quot;]/div[@class=&quot;cHndV&quot;]/div[2]/table[@class=&quot;JxWTa&quot;]/tbody[1]/tr[@class=&quot;xagVG&quot;]/td[@class=&quot;qIBX3 vpuDG&quot;]</value>
      <webElementGuid>46fcf07c-4d38-4913-958e-dc674142c006</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='base-layer']/main/div[2]/div[2]/table/tbody/tr/td[2]</value>
      <webElementGuid>7cefa7f6-4d0a-48cb-9df7-aeb3f476c4c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Authentication'])[1]/following::td[2]</value>
      <webElementGuid>3437a03b-9a5d-4243-8c19-2df52c4f517d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/following::td[2]</value>
      <webElementGuid>8e800a2c-c49c-4a17-a53b-e8e6500afdc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nawel Mele'])[2]/preceding::td[2]</value>
      <webElementGuid>fdc1cc3f-1dbb-4914-83b7-a368b9a7aa8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='nawel.mele@reach5.co']/parent::*</value>
      <webElementGuid>2e9c2fc1-7019-48de-9ffa-701ebc2e2ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>d37a00f7-3287-4ce5-a6b4-4ffec676c080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'nawel.mele@reach5.co' or . = 'nawel.mele@reach5.co')]</value>
      <webElementGuid>d8a7f281-a94c-4595-932b-16185e1f61d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
