<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_httpsinteg-qa-nme.reach5.netauth</name>
   <tag></tag>
   <elementGuidId>dfaf270f-9db5-4648-a584-33b5e32e9d1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.Gb0rW</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='base-layer']/main/div[2]/div[2]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;https://integ-qa-nme.reach5.net/auth&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f71f7c90-b39c-43e5-8181-600f2ad32513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>48435316-1b9f-40ac-a124-e735a2a5abfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Gb0rW</value>
      <webElementGuid>c882d6f5-a188-4a66-a285-11d0a37ec378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://integ-qa-nme.reach5.net/auth</value>
      <webElementGuid>34b73f3b-8668-450c-8b65-f98b948346ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://integ-qa-nme.reach5.net/auth</value>
      <webElementGuid>f0d57b61-dc75-45ed-a53b-2adf7686db11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;base-layer&quot;)/main[@class=&quot;d3KUA&quot;]/div[@class=&quot;cHndV Fnip4&quot;]/div[@class=&quot;PYQoT&quot;]/div[@class=&quot;OgSQ1&quot;]/a[@class=&quot;Gb0rW&quot;]</value>
      <webElementGuid>e8951da9-945c-457a-89b3-16d26ad27364</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='base-layer']/main/div[2]/div[2]/div[2]/a</value>
      <webElementGuid>a1fd9264-b5f0-4394-8cb1-6ad09b6b707a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'https://integ-qa-nme.reach5.net/auth')]</value>
      <webElementGuid>8d76b0fc-c554-4353-b313-0abf18477eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enabled'])[1]/following::a[1]</value>
      <webElementGuid>607a5854-a999-46a6-acc1-b28b8f39a7a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::a[1]</value>
      <webElementGuid>15962519-c023-4fcd-956e-5c57ee4bd9ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='https://integ-qa-nme.reach5.net/auth']/parent::*</value>
      <webElementGuid>a0d8e5dd-2445-475e-b265-7ae9e85ef777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://integ-qa-nme.reach5.net/auth')]</value>
      <webElementGuid>7bf22b8b-0af2-4ce8-addf-712a49895647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>c7b4e836-03bf-4db2-9bbf-d530521a7104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://integ-qa-nme.reach5.net/auth' and (text() = 'https://integ-qa-nme.reach5.net/auth' or . = 'https://integ-qa-nme.reach5.net/auth')]</value>
      <webElementGuid>16a8ad0a-6dfb-4e7d-85eb-d3f7a7701ef0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
