<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Settings</name>
   <tag></tag>
   <elementGuidId>6d4c65cc-31eb-4766-a05c-97afd76729e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.nav.navbar-nav > li.ng-scope > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/section/div[2]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Settings&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d1940162-8b38-42f6-ae46-224511097e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/QA-nme-katalon-testing/admin/settings</value>
      <webElementGuid>2aacef51-6a0d-43d7-80aa-62faebfb2203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Settings </value>
      <webElementGuid>e3c19854-3dee-4a4f-9640-14e6125176e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/section[@class=&quot;app-header navbar ng-scope&quot;]/div[@class=&quot;collapse pos-rlt navbar-collapse box-shadow bg-success ng-scope&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;ng-scope&quot;]/a[1]</value>
      <webElementGuid>32e13cf6-1816-4c20-ac0b-f862bb346006</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/section/div[2]/ul/li[2]/a</value>
      <webElementGuid>169dc5f7-86fc-4abd-8b2d-daa6b4940773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Settings')]</value>
      <webElementGuid>ae474f38-0feb-4dce-9d7a-2dde8c8d2431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reach5 Load Tests'])[1]/following::a[1]</value>
      <webElementGuid>b108ad10-6e04-4ea1-a02b-4b0cb5f05bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='documentation-official'])[1]/following::a[2]</value>
      <webElementGuid>6d102c6d-46d7-41ad-9aa1-98cf2253a10c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Root'])[1]/preceding::a[1]</value>
      <webElementGuid>a0097811-ceea-4977-b664-fdf816fa3485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nawel Mele'])[1]/preceding::a[2]</value>
      <webElementGuid>091b7e07-3ac4-427f-b30e-d1ac9a50d2ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Settings']/parent::*</value>
      <webElementGuid>ae50675d-8588-472c-8d67-0061ed916e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/QA-nme-katalon-testing/admin/settings')]</value>
      <webElementGuid>48c07b4c-96a7-43d6-b896-3ee8e15931c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>d97bf380-993d-4ce1-b972-231bf326eaa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/QA-nme-katalon-testing/admin/settings' and (text() = ' Settings ' or . = ' Settings ')]</value>
      <webElementGuid>791939b3-1097-4b8c-82d6-9130a4ec85fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
