<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Benjamin BergstromAY8Qoi3k7iLNPbxokzneU_d05121</name>
   <tag></tag>
   <elementGuidId>24a232e6-0ff7-424f-92b2-df0d56b5e9cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.cHndV > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='base-layer']/main/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.cHndV > div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4cf01b8a-2cc0-4220-adfc-875ba85ba728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Benjamin BergstromAY8Qoi3k7iLNPbxokzneUser idkatalonusergenerale@gmail.comThis email is not verifiedmaleGender37 years old (born the 1986/10/09)+33612345686This phone number is not verifiedGenderCreated at 2022-09-01 15:30:00Creation dateUpdated at 2024-04-24 17:03:34Last update0Login count0Friends0LikesCustom Fieldsfavorite_movie : favorite_number : Recent activityConsentsNo activity exists for this user.Filters</value>
      <webElementGuid>f7bd3da7-7d7b-4ec3-b2c2-e400806f8489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;base-layer&quot;)/main[@class=&quot;d3KUA&quot;]/div[@class=&quot;cHndV&quot;]/div[1]</value>
      <webElementGuid>6967e2d7-a602-4870-9000-d12700521885</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='base-layer']/main/div[2]/div</value>
      <webElementGuid>34fa17cf-3a0a-4ca3-88ae-29b6e2782836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[1]/following::div[2]</value>
      <webElementGuid>ea283dc6-c821-4bff-bb6c-d6fe820c106f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Details'])[1]/following::div[3]</value>
      <webElementGuid>bde0c087-7a82-4b73-a4aa-af169a2a04bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div[2]/div</value>
      <webElementGuid>17ce6a48-ddd2-44b0-8671-46ac9409863b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Benjamin BergstromAY8Qoi3k7iLNPbxokzneUser idkatalonusergenerale@gmail.comThis email is not verifiedmaleGender37 years old (born the 1986/10/09)+33612345686This phone number is not verifiedGenderCreated at 2022-09-01 15:30:00Creation dateUpdated at 2024-04-24 17:03:34Last update0Login count0Friends0LikesCustom Fieldsfavorite_movie : favorite_number : Recent activityConsentsNo activity exists for this user.Filters' or . = 'Benjamin BergstromAY8Qoi3k7iLNPbxokzneUser idkatalonusergenerale@gmail.comThis email is not verifiedmaleGender37 years old (born the 1986/10/09)+33612345686This phone number is not verifiedGenderCreated at 2022-09-01 15:30:00Creation dateUpdated at 2024-04-24 17:03:34Last update0Login count0Friends0LikesCustom Fieldsfavorite_movie : favorite_number : Recent activityConsentsNo activity exists for this user.Filters')]</value>
      <webElementGuid>f37460ba-8e14-418a-b4ce-b3ad346ccf0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
