<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter_Nr7Ji CVfQQ</name>
   <tag></tag>
   <elementGuidId>1098f21e-0b83-44e1-a53f-f335de9be88b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.Nr7Ji.CVfQQ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search by name, email, phone number, external ID, custom ID or ID&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b54f3a71-a1e8-4b13-a863-ba2931bad835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e8f19cb8-fd2d-463b-877f-29a620f2b8d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by name, email, phone number, external ID, custom ID or ID</value>
      <webElementGuid>acba2def-62e5-4866-8510-992d01b95510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Nr7Ji CVfQQ</value>
      <webElementGuid>ced529d3-4743-48e6-98af-fb93f90a97ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;base-layer&quot;)/main[@class=&quot;d3KUA&quot;]/div[@class=&quot;cHndV&quot;]/div[@class=&quot;wKnEZ&quot;]/div[@class=&quot;Wb55R&quot;]/input[@class=&quot;Nr7Ji CVfQQ&quot;]</value>
      <webElementGuid>63a993eb-fb06-4d9e-aa69-617739c714a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>b2641d69-0d9a-4f84-bc64-0c05f4453bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='base-layer']/main/div[2]/div/div/input</value>
      <webElementGuid>a58b1fdf-298f-45f6-8bab-20d7a7f8553b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>5466c232-9f52-4b58-8e1c-2382dc0c62a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search by name, email, phone number, external ID, custom ID or ID']</value>
      <webElementGuid>4eb6b83f-5361-4fa9-968d-e32521e45a1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
