<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Filters</name>
   <tag></tag>
   <elementGuidId>efae3a3b-d9ac-4f3b-b2b8-067bc14cfc14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.z3Q7p.gkNlq.Me0lj > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='base-layer']/main/div[2]/div/div[2]/div/div[2]/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Filters&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>587b417f-f757-45d3-8cc6-44a5f4bae860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filters</value>
      <webElementGuid>0a71ef75-c2b2-4062-a8ae-251d2c905b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;base-layer&quot;)/main[@class=&quot;d3KUA&quot;]/div[@class=&quot;cHndV&quot;]/div[1]/div[2]/div[@class=&quot;wiDxe&quot;]/div[@class=&quot;PYQoT&quot;]/div[1]/button[@class=&quot;z3Q7p gkNlq Me0lj&quot;]/span[1]</value>
      <webElementGuid>f890cc73-cb3f-4991-b7d2-656ec535bc9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='base-layer']/main/div[2]/div/div[2]/div/div[2]/div/button/span</value>
      <webElementGuid>93ea5571-b4f3-47fd-b1d6-30f4f1c83c7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No activity exists for this user.'])[1]/following::span[1]</value>
      <webElementGuid>18729e06-8212-4630-988e-032c42a5a8d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consents'])[1]/following::span[2]</value>
      <webElementGuid>dc9ccbe6-ff80-4400-9122-f40e68991fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Filters']/parent::*</value>
      <webElementGuid>e47f0ed5-d26e-4b25-b2cd-1c1b479c1650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button/span</value>
      <webElementGuid>b8615b0d-f3c9-4b33-8b11-185fe9f2486e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Filters' or . = 'Filters')]</value>
      <webElementGuid>3ff2d1ae-2e1b-4d07-8b11-ec5784f5ee82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
