<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_None_css-8mmkcg</name>
   <tag></tag>
   <elementGuidId>2928570b-bbaa-4e31-9913-dbb23f0b4416</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-10j1lnc-indicatorContainer > svg.css-8mmkcg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='None'])[1]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#popup-layer svg >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>8148f4e1-2255-4c55-a61b-f739b819116e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>c8c4d614-226b-4c80-b637-55deb5bc0b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>ed44a7ce-c08f-4374-a9aa-63b9d46125a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 20 20</value>
      <webElementGuid>c4bb31d3-7acb-4a4a-883b-5559bc430f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8c3400b2-98f4-4214-8cda-b50c5163d92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c2091056-474f-45dc-a669-2a4fa7270588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-8mmkcg</value>
      <webElementGuid>ee0e4e98-c547-4a47-b082-1b4e65e6aa11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popup-layer&quot;)/div[@class=&quot;COmzk&quot;]/div[@class=&quot;biIbb EU84j&quot;]/div[@class=&quot;oZAtY&quot;]/div[@class=&quot;ugKnP css-b62m3t-container&quot;]/div[@class=&quot;css-1p8hvqr-control&quot;]/div[@class=&quot;css-1wy0on6&quot;]/div[@class=&quot;css-10j1lnc-indicatorContainer&quot;]/svg[@class=&quot;css-8mmkcg&quot;]</value>
      <webElementGuid>7a8b1c5e-6eaa-461e-9909-ce9d39283efa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='None'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>e42f3ec1-e4ce-4946-8355-5286d8f98fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login, 1 of 2.'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>24b830a9-71f9-441d-a769-f577c5ee49fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>9fe741c1-bbdc-4e7e-8a68-2cd190b0ce23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='None'])[2]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>ea1f1c43-a0b1-44f3-9d5a-8d1f204c553f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
