<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_Hp_Login_with_Custom_identifier</name>
   <tag></tag>
   <elementGuidId>d84af6ab-b9c7-4764-b07e-802e3df7b98a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'password' and @type = 'password' and @placeholder = 'Password' and @title = 'Password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ldsouG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ldsouG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;password&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3282b6d-262a-480b-a7ed-a43cd5dd591e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ldsouG</value>
      <webElementGuid>8a2ff7d9-35ed-4e8d-a830-d63be3b5bffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>02abc10a-6248-4dd7-b20b-1e03c073193d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>bd6a4dc9-d7da-4dd3-8a10-6039cde34d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>ea3256a9-9496-40c9-84c6-c85db1e9905c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>current-password</value>
      <webElementGuid>edd336d4-b679-462e-a742-003f1c022656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>753cd17d-b418-4a93-9216-3ac93e452daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8f7d29cb-f44d-4f1b-ba94-59729df0601f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fzqBZW gCdQQl</value>
      <webElementGuid>2fdc36cc-1042-4a78-92a1-5bb64ffd6ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ldsouG&quot;)</value>
      <webElementGuid>009f04af-b327-46b0-960b-66b5a90dd4e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ldsouG']</value>
      <webElementGuid>6e9fa885-126f-4ad1-a196-4e0555614fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='widget-container']/div/div/form/div[4]/div/input</value>
      <webElementGuid>c9ec2ba9-e0e2-497c-9d09-d7a9174e6b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>f8524ab4-c145-4368-a88c-594e62d5dd54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ldsouG' and @name = 'password' and @type = 'password' and @placeholder = 'Password' and @title = 'Password']</value>
      <webElementGuid>d7f3c192-9726-496e-b3b1-1e44da088d7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
