<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_or_customIdentifier</name>
   <tag></tag>
   <elementGuidId>81e81bb4-32dc-4e51-9e23-d4758a36b51a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'customIdentifier' and @type = 'text' and @placeholder = 'customIdentifier']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nDuOiA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nDuOiA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;customIdentifier&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4175396d-5610-42ef-a9d0-b9fb0a64891c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nDuOiA</value>
      <webElementGuid>449cdd86-6663-4b34-a17e-98036e0cc17d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customIdentifier</value>
      <webElementGuid>84642525-a301-4d5b-a66a-8ee0b64e89aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>572e0613-e37a-40b5-8c84-596ac2535c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>customIdentifier</value>
      <webElementGuid>39548415-10e9-4504-95f6-c5b87fa802c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>customIdentifier</value>
      <webElementGuid>c83c8265-3012-4a3b-ae62-1945fa00ff53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fzqBZW gCdQQl</value>
      <webElementGuid>66e8a985-99b7-491f-b81a-91bd0691b07b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nDuOiA&quot;)</value>
      <webElementGuid>8d692bf5-af63-4476-96ad-1c0c94cf8004</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nDuOiA']</value>
      <webElementGuid>12b71c0f-fdc2-454d-ada0-411b1e74e6ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='widget-container']/div/div/form/div[3]/input</value>
      <webElementGuid>3deefd0c-5fe6-4327-a527-a3a346f4eea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>198232d1-a8ac-4c95-9f09-8b8adf31d63e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nDuOiA' and @name = 'customIdentifier' and @type = 'text' and @placeholder = 'customIdentifier']</value>
      <webElementGuid>89bc3511-20ed-43b7-a422-55529acadd26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
