<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_165K profilesFilter</name>
   <tag></tag>
   <elementGuidId>e1d20b0e-89f8-4a9d-a62b-1bf7d9171b86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.W9Owb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='base-layer']/main/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;165K profilesFilter&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>41a1f468-bf88-4a16-a710-090a6646c76a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>W9Owb</value>
      <webElementGuid>811ffcbe-de9a-4069-83f2-3241b0af93c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>165K profilesFilter</value>
      <webElementGuid>baa81e5c-e211-4735-ba2a-d91a9aa68476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;base-layer&quot;)/main[@class=&quot;d3KUA&quot;]/div[@class=&quot;W9Owb&quot;]</value>
      <webElementGuid>a5fed9dd-bc06-44ef-8d76-ba0addc274bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='base-layer']/main/div</value>
      <webElementGuid>7c52eb28-a651-4fc2-81b5-0eee1ee837c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nawel Mele'])[1]/following::div[2]</value>
      <webElementGuid>3c430925-9be1-4e62-9335-50308eca8fe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Root'])[1]/following::div[4]</value>
      <webElementGuid>50375fe5-3c00-46ad-bee4-c49d74bdd102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identifier'])[1]/preceding::div[4]</value>
      <webElementGuid>4f950d50-07a7-4848-8c08-029cfb077921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div</value>
      <webElementGuid>c694ff7a-04a7-4021-94fd-053208e0a2f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '165K profilesFilter' or . = '165K profilesFilter')]</value>
      <webElementGuid>9ba17245-542d-4148-9cb7-3cfd3b5637df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
