<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UseProfileEditionTitle</name>
   <tag></tag>
   <elementGuidId>c96cc0c2-c100-4e52-ada2-e8f55bb44b18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.i_mr5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popup-layer']/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Edition of profile Benjamin Bergstrom&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>f9cabe95-c949-4c95-9894-c197f576a2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>i_mr5</value>
      <webElementGuid>31ea133f-79ab-4cc7-9b5d-4fbe549ce79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edition of profile Benjamin Bergstrom</value>
      <webElementGuid>5b026a42-458a-404b-97a0-a84d4a828135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popup-layer&quot;)/div[@class=&quot;COmzk&quot;]/div[@class=&quot;biIbb&quot;]/p[@class=&quot;i_mr5&quot;]</value>
      <webElementGuid>159891cc-1724-4d7a-9fe2-edef5e7c41cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup-layer']/div/div/p</value>
      <webElementGuid>9a6bf7b0-dc27-40df-a542-a62ad8a1e6b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filters'])[1]/following::p[1]</value>
      <webElementGuid>7fb67dbd-0522-442e-a384-7cc62df82592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No activity exists for this user.'])[1]/following::p[1]</value>
      <webElementGuid>f8526784-ab2e-48a4-b40e-7c5d13d00879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic Infos'])[1]/preceding::p[1]</value>
      <webElementGuid>25d543f0-4b9c-46a7-aab6-8a8bd5d5e752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edition of profile Benjamin Bergstrom']/parent::*</value>
      <webElementGuid>b9357f5c-e8cc-4798-9629-c406d1d5f11f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>b3c1c17b-3051-45e5-9afe-55b728065833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Edition of profile Benjamin Bergstrom' or . = 'Edition of profile Benjamin Bergstrom')]</value>
      <webElementGuid>ed97171d-53d9-4186-b75b-eba62d4e5870</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
