name: Katalon Test Suite Collection 1
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v3.0
      with:
          version: '9.4.0'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -browserType="Chrome" -testcloudEnvironmentId="256" -statusDelay=15 -testSuiteCollectionPath="Test Suites/Test Suite Collection 1" -apiKey= ${{ secrets.KATALON_API_KEY }} --config -webui.autoUpdateDrivers=true'
