name: Katalon Test Suite Collection (testcloud)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        OsBrowser: [377,372,373,339,107]
        include:
          - os: macos-latest
            OsBrowser: 377
          - os: macos-latest
            OsBrowser: 339
          - os: macos-latest
            OsBrowser: 107
          - os:  windows-latest
            OsBrowser: 372
          - os:  windows-latest
            OsBrowser: 373
          
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
    - name: Get Info 
      run: echo "${{ matrix.os }} - ${{ matrix.OsBrowser }}"
    - name: Checkout
      uses: actions/checkout@v4
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v3.0
      with:
          version: '9.5.0'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -browserType="TestCloud" -testcloudEnvironmentId="${{matrix.OsBrowser}}" -testcloudTunnel="false" -statusDelay=15 -executionProfile="integ" -testSuiteCollectionPath="Test Suites/Test collection Console R5" -orgID=1450756 -apiKey=${{secrets.KATALON_API_KEY}} -testOpsReleaseId=658459 -testOpsProjectId=1423873 --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -webui.autoUpdateDrivers=true'
