name: Katalon Test Suite Collection (testcloud)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      max-parallel: 1
      matrix:
        OsBrowser: [377,107,339,372,373]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v3.0
      with:
          version: '9.5.0'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -browserType="TestCloud" -testcloudEnvironmentId="${{matrix.OsBrowser}}" -testcloudTunnel="false" -statusDelay=15 -executionProfile="integ" -testSuitePath="Test Suites/HP Test Suite" -orgID=1450756 -apiKey=${{secrets.KATALON_API_KEY}} -testOpsReleaseId=658459 -testOpsProjectId=1423873 --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -webui.autoUpdateDrivers=true'
