<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Analytics</name>
   <tag></tag>
   <elementGuidId>5239c802-2e3e-4b7e-8fec-0d9245451576</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.D6HWT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='base-layer']/header/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Analytics&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2a49e3cc-cae8-4e67-bf98-21068afc8a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>D6HWT</value>
      <webElementGuid>e9650051-e0d9-4bf4-956d-9f958c734ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/QA-nme-katalon-testing/home</value>
      <webElementGuid>cd27748a-722b-4e63-ad12-a582ccb7bc22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nav</name>
      <type>Main</type>
      <value>ignore</value>
      <webElementGuid>0ee94b0f-eddc-40dc-9acb-65d44a7b7d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Analytics</value>
      <webElementGuid>a6b3fbc9-d8a3-46dd-b8f0-e87311f039aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;base-layer&quot;)/header[@class=&quot;UOkzl&quot;]/div[@class=&quot;maUyO&quot;]/a[@class=&quot;D6HWT&quot;]</value>
      <webElementGuid>802876b2-2de0-43a7-9ff6-b3d6d3510f84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='base-layer']/header/div/a</value>
      <webElementGuid>c570d9c2-079a-4b2f-bae9-08b20addf5cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Analytics')]</value>
      <webElementGuid>983ba30e-a871-43fa-9305-aa0d7ea16ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='integ-qa-nme'])[1]/following::a[1]</value>
      <webElementGuid>0b6fc048-2f84-489e-9785-eb40a28abc3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced settings'])[1]/following::a[1]</value>
      <webElementGuid>02df4d9e-d62f-4c8a-aa8f-2375f22beefd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Root'])[1]/preceding::a[1]</value>
      <webElementGuid>e88c9f7c-a1ed-4b61-8b87-91cdff958449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nawel Mele'])[1]/preceding::a[2]</value>
      <webElementGuid>66d4824f-9450-414b-b391-419f8a195137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Analytics']/parent::*</value>
      <webElementGuid>bb85810d-8616-482c-bbb4-834494ca515d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/QA-nme-katalon-testing/home')]</value>
      <webElementGuid>77175858-721d-4ebb-a5d2-fa014ef157c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>3fa79881-6979-4446-b0ba-8c9ab6a68628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/QA-nme-katalon-testing/home' and (text() = 'Analytics' or . = 'Analytics')]</value>
      <webElementGuid>40d9ee15-6147-4ca1-99d7-86d3d1b05635</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
