<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_httpsinteg-qa-fonctionnelle.reach5.netauth</name>
   <tag></tag>
   <elementGuidId>bd4b658a-1815-4084-ac78-a10b134e392b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='base-layer']/main/div[2]/div[2]/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.Gb0rW</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;https://integ-qa-fonctionnelle.reach5.net/auth&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>81f04dc1-9bf7-4962-b0cf-a7f2c40ac8b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>77e3bbbc-b3f9-4162-9a8a-361a1dd2463c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Gb0rW</value>
      <webElementGuid>07abeca2-01c6-4a8f-bf23-4124427036d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://integ-qa-fonctionnelle.reach5.net/auth</value>
      <webElementGuid>6768e8d2-902f-4ff7-8067-1ae02fbf519e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://integ-qa-fonctionnelle.reach5.net/auth</value>
      <webElementGuid>3f3f01c8-fca1-4838-9fe7-0fb47340f030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;base-layer&quot;)/main[@class=&quot;d3KUA&quot;]/div[@class=&quot;cHndV Fnip4&quot;]/div[@class=&quot;PYQoT&quot;]/div[@class=&quot;OgSQ1&quot;]/a[@class=&quot;Gb0rW&quot;]</value>
      <webElementGuid>07f14bd0-d007-4c21-b738-f7edb5a45446</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='base-layer']/main/div[2]/div[2]/div[2]/a</value>
      <webElementGuid>1923df74-3cae-43f2-94f0-5f407b9eb66d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'https://integ-qa-fonctionnelle.reach5.net/auth')]</value>
      <webElementGuid>3f0e4a20-0442-4dc7-aa8c-a6f7e201ea11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enabled'])[1]/following::a[1]</value>
      <webElementGuid>0b410f66-37a7-40b3-a66d-7aa11a2f28ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::a[1]</value>
      <webElementGuid>e28ccf8f-76a1-4771-adbf-b41d1731b9f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='https://integ-qa-fonctionnelle.reach5.net/auth']/parent::*</value>
      <webElementGuid>e90d0b3f-271f-464c-b8fb-2ef3895db29a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://integ-qa-fonctionnelle.reach5.net/auth')]</value>
      <webElementGuid>ddd49518-66c7-4c68-92ee-be77d9162c61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>7ab8f13a-01ac-4e34-ae2d-35cca8395023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://integ-qa-fonctionnelle.reach5.net/auth' and (text() = 'https://integ-qa-fonctionnelle.reach5.net/auth' or . = 'https://integ-qa-fonctionnelle.reach5.net/auth')]</value>
      <webElementGuid>37ff9dba-9871-48f7-ad98-672a76342359</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
