<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_httpsinteg-qa-nme.reach5.netauth</name>
   <tag></tag>
   <elementGuidId>1b8a4276-d9dd-44d5-9057-4d3b50e106c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.Gb0rW</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='base-layer']/main/div[2]/div[2]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4bc4367a-09b6-479e-a86f-8c2c1d1f6e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>65d1e16e-9c36-4126-95fb-079592752dd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Gb0rW</value>
      <webElementGuid>0797a3c8-0be6-4d96-9dea-861e880c32c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://integ-qa-nme.reach5.net/auth</value>
      <webElementGuid>fc4a4a62-ed33-4f38-b216-7e5270f674a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://integ-qa-nme.reach5.net/auth</value>
      <webElementGuid>bb2c594f-3368-4334-b938-249dd4a418b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;base-layer&quot;)/main[@class=&quot;d3KUA&quot;]/div[@class=&quot;cHndV Fnip4&quot;]/div[@class=&quot;PYQoT&quot;]/div[@class=&quot;OgSQ1&quot;]/a[@class=&quot;Gb0rW&quot;]</value>
      <webElementGuid>2db06cf4-6afc-4638-a3ef-442aebcc37b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='base-layer']/main/div[2]/div[2]/div[2]/a</value>
      <webElementGuid>67bacbbd-6bce-4f06-9d56-9f3a462389ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'https://integ-qa-nme.reach5.net/auth')]</value>
      <webElementGuid>3b7358e0-cc3f-4b6c-b465-802290769a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enabled'])[1]/following::a[1]</value>
      <webElementGuid>e89e8d26-1c1f-4c9c-82f9-8aeb2599e43d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::a[1]</value>
      <webElementGuid>1ff13947-b45f-42a0-9702-f8ae47c9d22b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='https://integ-qa-nme.reach5.net/auth']/parent::*</value>
      <webElementGuid>37bfcad3-2d71-4487-99aa-ec8c515e5a18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://integ-qa-nme.reach5.net/auth')]</value>
      <webElementGuid>9218194a-7a2f-48a3-8a34-dca8c46e0e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>41f320b3-c1fe-486a-b91f-59cfcc4d54e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://integ-qa-nme.reach5.net/auth' and (text() = 'https://integ-qa-nme.reach5.net/auth' or . = 'https://integ-qa-nme.reach5.net/auth')]</value>
      <webElementGuid>58b92ae1-07f3-4e70-8e31-a0c757c86dfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
