<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_or_customIdentifier_1</name>
   <tag></tag>
   <elementGuidId>3d19f488-e705-48f8-b81f-69dc6c758ef2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RSoldu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RSoldu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;customIdentifier&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>806b2537-fb38-4e1c-855f-b900799e6134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RSoldu</value>
      <webElementGuid>ea3db323-ec45-4d06-8f27-8f4e6a21c16d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customIdentifier</value>
      <webElementGuid>a7e58af9-713e-4b8d-905c-30fd61049e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bd9eebde-b7d9-48fa-b4de-5c225d81f362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>customIdentifier</value>
      <webElementGuid>07c819d5-656f-43e1-97b9-0c19824e9a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>customIdentifier</value>
      <webElementGuid>82ca0bf5-a630-40a0-82ac-4cbcb394f00a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fzqBZW gCdQQl</value>
      <webElementGuid>74daa0e0-6bee-4ef9-a472-bca2f734975a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RSoldu&quot;)</value>
      <webElementGuid>d7116905-6b67-4e7f-8ba0-7d5acd2ebd59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RSoldu']</value>
      <webElementGuid>b13f2ee5-e222-4d1b-869a-0b99d1f438a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='widget-container']/div/div/form/div[3]/input</value>
      <webElementGuid>7bca1654-8a6e-4326-b95d-319752c95ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>a6c8855b-dbb1-42f3-9b62-8a6c49f8e5d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'RSoldu' and @name = 'customIdentifier' and @type = 'text' and @placeholder = 'customIdentifier']</value>
      <webElementGuid>f0b1b58f-ad1f-41e0-939b-b9d57c62ef03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
