<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last name_familyName</name>
   <tag></tag>
   <elementGuidId>962d2ea8-f0b3-442f-8c3d-85085d016f7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='YKkEwb']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#YKkEwb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;familyName&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d668f52-7e41-4d06-9d1f-0d08cbd32d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>YKkEwb</value>
      <webElementGuid>1b784460-7366-4ad6-b4f2-ce80e5108a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>familyName</value>
      <webElementGuid>a0a5d921-ffa1-4454-8657-cfde76e957bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last name</value>
      <webElementGuid>3cbc8993-90c9-476c-993c-69fc1f7bbecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Last name</value>
      <webElementGuid>653ea437-aa51-4258-8503-e936a41e3416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>familyName</value>
      <webElementGuid>8eb8ae1d-b45b-4750-a324-6de27bd2fbdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fzqBZW gCdQQl</value>
      <webElementGuid>00f2ac2e-acd1-4fb7-802f-b979bc35fbfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;YKkEwb&quot;)</value>
      <webElementGuid>7c64a93d-212b-4464-acb4-57de0729c18d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='YKkEwb']</value>
      <webElementGuid>6bad0954-77e0-4bb4-8e0c-98921e6fe9ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='widget-container']/div/div/form/div[3]/input</value>
      <webElementGuid>04190daf-ad22-4fe2-ae4a-1035f8af97b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>6222ee5c-aef9-463d-a39f-38291993563b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'YKkEwb' and @name = 'familyName' and @placeholder = 'Last name' and @title = 'Last name']</value>
      <webElementGuid>ac7bf903-eef5-4c89-8f8b-911bb6eff5c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
