<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_or_customIdentifier</name>
   <tag></tag>
   <elementGuidId>ca3e09cb-7212-4d43-98f2-b5a1a0a8e2b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nDuOiA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nDuOiA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d203ddb-e4bf-4a47-81d4-89fd9a2dd40d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nDuOiA</value>
      <webElementGuid>2e15f664-e702-44aa-b6f1-c7f5fc0eab28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customIdentifier</value>
      <webElementGuid>661aa653-ebd3-4f1f-a1d0-4965505ed45b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>87021b33-836f-4dbe-bfb5-072124131884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>customIdentifier</value>
      <webElementGuid>a522758a-bf3c-41d1-b597-b3c15c5c421a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>customIdentifier</value>
      <webElementGuid>dd62fac8-3f28-4c64-83ff-44c7c0161260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fzqBZW gCdQQl</value>
      <webElementGuid>74b69d0b-27f8-4acd-a807-05c485af1b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nDuOiA&quot;)</value>
      <webElementGuid>033e42cb-da55-40a7-9ab0-3b0960209ba0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nDuOiA']</value>
      <webElementGuid>26af9910-701c-459e-931b-a0a63abc8e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='widget-container']/div/div/form/div[3]/input</value>
      <webElementGuid>ff32040a-58ad-48d8-abc2-ac1118f91567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>57f4d5de-edea-40dc-9092-26b12357a9cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nDuOiA' and @name = 'customIdentifier' and @type = 'text' and @placeholder = 'customIdentifier']</value>
      <webElementGuid>1f192811-56b1-423a-b7e0-44f15872c446</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
