<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Hosted Pages</name>
   <tag></tag>
   <elementGuidId>b217771a-e313-494c-9cec-c8d5b085ba63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='base-layer']/nav/div/div/span[4]/a/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span:nth-of-type(4) > a.ZEeIZ > div.IKMED > span.m71by</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Hosted Pages&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>35b1fa75-d53e-4160-a31c-8f1609dd8725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m71by</value>
      <webElementGuid>330c827b-12b5-484d-8777-3edf0e0e7eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hosted Pages</value>
      <webElementGuid>7d1f8662-b4c6-4e37-b481-57eef77a46c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;base-layer&quot;)/nav[@class=&quot;xhik7&quot;]/div[@class=&quot;NI0dP&quot;]/div[1]/span[4]/a[@class=&quot;ZEeIZ&quot;]/div[@class=&quot;IKMED&quot;]/span[@class=&quot;m71by&quot;]</value>
      <webElementGuid>2e06a055-ba63-4af5-936a-42ffb2e17c26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='base-layer']/nav/div/div/span[4]/a/div/span</value>
      <webElementGuid>8a843b60-71f0-4ba0-b2ff-3bcc2018dfb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Custom scopes'])[1]/following::span[2]</value>
      <webElementGuid>ad852e87-7b94-4885-acc0-02fb692442a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clients'])[1]/following::span[4]</value>
      <webElementGuid>309ae28a-45d2-443e-a0aa-cdc4e8075a0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Security'])[1]/preceding::span[1]</value>
      <webElementGuid>72c4feaa-2eed-4467-910d-74af0d206716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Providers'])[1]/preceding::span[3]</value>
      <webElementGuid>dcbba417-5101-49d3-bac4-a91de5b896b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hosted Pages']/parent::*</value>
      <webElementGuid>5235aba9-cb20-43c8-a825-2da06aef5920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]/a/div/span</value>
      <webElementGuid>27d236c7-9c8b-47f3-992f-816a142f090f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Hosted Pages' or . = 'Hosted Pages')]</value>
      <webElementGuid>900eba7e-fb56-4c22-aa25-cf5170eedb1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
